### PR TITLE
Changes to support DNS glue, much better topology based logic, health…

### PR DESCRIPTION
**Pull request by mattackerman808**
Large PR with changes I have made to polaris to support my use case. I had hopes we can keep our code from forking to far from the upstream.

This is the list of changes:

Support for NS records and glue records to allow a domain to be fully delegated to Polaris. This requires some config file modifications. Adds the 'nsrecord' tag to determine if a global name should return a NS record.

Support for new health check type of 'None' , this forces members to be online and performs no health checking. This is mainly used for testing or for large pools that don't require health checks.

Bump up max responses to 100 and raise the TTL for the default SOA to slow down request rates. Possible this should be moved to a config item.

Add new 'checkConfig' option to startup. This causes the init script to verify the configuration is valid before doing a reload.

Much better topology based load balancing. Previously the script was just doing a matchin for loop. Changed this to find the most specific subnet match in the case of overlapping subnets. This adds a python library requirement (netaddr)

Fixed some formatting on status outputs on scripts.

Removed many extra spaces from code.

### CODE REVIEW

**Comment by antongavrik** [comment]
Thanks, will get this reviewed at some point.

**Comment by antongavrik** [comment]
Some of these excellent features have already been added into 0.5 branch, I might have follow up questions for other ones.

>Much better topology based load balancing. Previously the script was just doing a matchin for loop. Changed this to find the most specific subnet match in the case of overlapping subnet

Could you provide an example scenario of overlapping subnets as it relates to an infrastructure being GSLB-ed?

**Comment by antongavrik** [comment]
Same for "nsrecord" feature, please provide an example.

The rest of the features are included in 0.5 release.

**Comment by mattackerman808** [comment]
We have a (very) large network assigned to us and quite often subnets overlap. We also wanted a default 'catch all' subnet as well. The logic put into this PR finds the most specific subnet in the config and matches with that. You could have 1.2.3.0/24 defined and also 1.2.3.128/25.

The nsrecord / glue feature allows you to delegate an entire domain / subdomain to the polaris servers without requiring a NS record for every entry. This is more of the traditional 'GTM' setup found in things like the F5 product.

Both of these were requirements for our environment.

**Comment by antongavrik** [comment]
>You could have 1.2.3.0/24 defined and also 1.2.3.128/25

Would these be the same region or different regions in Polaris config?

**Comment by mattackerman808** [comment]
The PR I proposed would address them being in different regions.

10.0.0.0/16 - Site A
10.0.10.0/24 - Site B
10.0.10.128/25 - Site C

For example.

**Comment by antongavrik** [comment]
The PR proposes to return both NS records and glue records, but it is my understanding, please correct me if I am wrong, that the glue records are only required if we wanted to perform a further sub delegation from Polaris to another set of name servers. In order to be able to delegate a zone to Polaris itself all is needed for Polaris to return SOA/NS records.

In order to minimize changes to the existing configuration, I am thinking of introducing a new top level stanza "zonenames". When a query comes in matching a zonename Polaris will provide NS records(but no glue) in addition to A records.

SOA behavior will remain unchanged for now.

CC @mschirrmeister who requested being able to configure NS in the past.

Let me know what do you think.

pools:
    www-example:
        monitor: http
        lb_method: wrr 
        members:
        - ip: 10.1.1.10
          name: www1
        - ip: 192.168.1.10
          name: www2

    ns1-example:
        # forced is a new monitor type in v0.5 that disables health checking
        monitor: forced
        lb_method: wrr
        members:
        - ip: 10.1.1.1
          name: ns1

    ns2-example:
        monitor: forced
        lb_method: wrr
        falback: any
        members:
        - ip: 192.168.1.1
          name: ns2

globalnames:
    ns1.example.com:
        pool: ns1-example
        ttl: 14400

    ns2.example.com:
        pool: ns2-example
        ttl: 14400

    www.example.com:
        pool: www-example
        ttl: 1

zonenames:
    example.com
        pool: www-example
        ttl: 1
        nameservers:
        - name: ns1.example.com
          ttl: 14400
        - name: ns2.example.com
          ttl: 14400

**Comment by antongavrik** [comment]
As this feature requires a little bit more consideration, I'll leave it out until v0.6, all other changes here, including topology changes were implemented as part of v0.5, available in 0.5 branch and to be released soon.

**Comment by mattackerman808** [comment]
Per RFC when requesting NS records the authoritative resolver should also provide A records. This is what 'glue' is.

For example:

$ dig ns google.com @ns3.google.com

; <<>> DiG 9.8.3-P1 <<>> ns google.com @ns3.google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 34039
;; flags: qr aa rd; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 4
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;google.com.			IN	NS

;; ANSWER SECTION:
google.com.		345600	IN	NS	ns1.google.com.
google.com.		345600	IN	NS	ns2.google.com.
google.com.		345600	IN	NS	ns3.google.com.
google.com.		345600	IN	NS	ns4.google.com.

;; ADDITIONAL SECTION:
ns1.google.com.		345600	IN	A	216.239.32.10
ns2.google.com.		345600	IN	A	216.239.34.10
ns3.google.com.		345600	IN	A	216.239.36.10
ns4.google.com.		345600	IN	A	216.239.38.10

;; Query time: 38 msec
;; SERVER: 216.239.36.10#53(216.239.36.10)
;; WHEN: Tue Apr 11 14:32:58 2017
;; MSG SIZE  rcvd: 164

DNS will work without it, but it can cause zone inconsistency and also forces the resolver to do more work.

**Comment by antongavrik** [comment]
https://github.com/polaris-gslb/polaris-gslb/issues/35 is opened to track DNS glue changes, the rest of the changes released in v0.5.

**Pull request closed without merging**
